name: Tauri Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App version (e.g. 0.1.0)"
        required: true
      release_notes:
        description: "Release notes"
        required: false
        default: ""

env:
  VERSION: ${{ github.event.inputs.version }}
  RELEASE_NOTES: ${{ github.event.inputs.release_notes }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Deploy to Google Play

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install pnpm + deps
        run: |
          npm i -g pnpm
          pnpm install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125"

      - name: Prepare Android keystore
        run: |
          mkdir -p src-tauri/gen
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > src-tauri/gen/upload-keystore.jks

      - name: Write keystore.properties
        run: |
          cat <<EOF > src-tauri/gen/keystore.properties
          storeFile=${{ github.workspace }}/src-tauri/gen/upload-keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build Tauri Android (Release, arm64-v8a)
        env:
          TAURI_ANDROID_KEYSTORE: ${{ github.workspace }}/src-tauri/gen/upload-keystore.jks
          TAURI_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          TAURI_ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          TAURI_ANDROID_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: pnpm tauri android build --target aarch64 --release

      - name: Decode Google Play service account
        run: echo "${{ secrets.GOOGLE_PLAY_KEY }}" | base64 -d > /tmp/play-account.json

      - name: Upload to Google Play Internal Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: /tmp/play-account.json
          packageName: com.yourcompany.yourapp  # <-- set your package id
          # If APK is produced (default for many Tauri templates):
          releaseFiles: src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk
          # If you configure bundle (AAB), use:
          # releaseFiles: src-tauri/gen/android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          releaseName: v${{ github.event.inputs.version }}
